services:

  backend:
    build: ./
    ports:
      - "8081:8080"
    networks:
      - app-network

  postgree:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin1234"
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge